#config server configuration start
spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        # native:
          # search-locations: "classpath:/config"
          # search-locations: "file:///Users//eazybytes//Documents//config" ==> external yml file(we can put yml any location)
        git:
          uri: "https://github.com/eazybytes/eazybytes-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
#for service bus
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
#actutaor
management:
  endpoints:
    web:
      exposure:
        include: "*"
#this properties monitor health of configserver application
  health:
    #check config server application is able to accept request or not
    readiness-state:
      enabled: true
    #check config server application is up or not
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
#used to encrypt properties value.
encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"
#config server configuration end
server:
  port: 8071
